crawler.public.portfolio.simu.template:
    params_spec:
        symbols:
            default: '*'
        quant_data:
            default: stock
        cache_path:
            default: 'source/public/portfolio/simu/history'
        crawler_class:
            default: PublicSimuMainHoldCrawler
        crawler_module:
            default: public_portfolio_crawler.simu
        debug:
            default: false

    job_template: |
        type: crawler

        schdule:
            resource:
                domain: public
            queue:
                crawler.domain.simu #not so sure

        debug: {{ debug }}
        max_fail: 8
        show_memory_stats: false
        chain_subtask_result: false

        quant_data: {{ quant_data }}
        symbols: {{ symbols | tojson }}
        timeout: 8

        cache_path: {{ cache_path }}

        output:
            stream: core.{{ quant_data }}.simu
            type: simple

        crawler_event:
            name: public.simu
            expire:
                days: 4

        crawler: 
            class: {{ crawler_class }}
            module: {{ crawler_module }}
            kwargs:
                plugins:
                -   class: SleepPlugin
                    kwargs:
                        exception_sleep: 30
                        sleep: 5
                -   class: RetryPlugin
                    kwargs:
                        max_retry: 4
                    

crawler.public.portfolio.simu.mainhold.monthly.debug:
    template: crawler.public.portfolio.simu.template
    params:
        symbols:
            - STOCK
        quant_data: stock
        cache_path: 'source/public/portfolio/simu/simumainhold/monthly'
        crawler_class: PublicSimuMainHoldCrawler
        crawler_module: public_portfolio_crawler.simu
        debug: true

crawler.public.portfolio.simu.advisor.monthly.debug:
    template: crawler.public.portfolio.simu.template
    params:
        symbols:
            - STOCK
        quant_data: stock
        cache_path: 'source/public/portfolio/simu/advisor/monthly'
        crawler_class: PublicSimuAdvisorCrawler
        crawler_module: public_portfolio_crawler.simu
        debug: true

crawler.public.portfolio.simu.im.monthly.debug:
    template: crawler.public.portfolio.simu.template
    params:
        symbols:
            - STOCK
        quant_data: stock
        cache_path: 'source/public/portfolio/simu/im/monthly'
        crawler_class: PublicSimuImCrawler
        crawler_module: public_portfolio_crawler.simu
        debug: true

crawler.public.portfolio.simu.pep.monthly.debug:
    template: crawler.public.portfolio.simu.template
    params:
        symbols:
            - STOCK
        quant_data: stock
        cache_path: 'source/public/portfolio/simu/pep/monthly'
        crawler_class: PublicSimuPepCrawler
        crawler_module: public_portfolio_crawler.simu
        debug: true
